### ISSUE TITLE
build failure on ubuntu 10.04

### ISSUE THREAD

**Issue by qwang-sj** [guokr/gkseg#2]
CC: wapiti.c --> wapiti
/tmp/ccuPItVc.o: In function `grd_domaxent':
gradient.c:(.text+0x1666): undefined reference to`__sync_bool_compare_and_swap_8'
gradient.c:(.text+0x16b9): undefined reference to `__sync_bool_compare_and_swap_8'
/tmp/ccuPItVc.o: In function`grd_subemp':
gradient.c:(.text+0x17c9): undefined reference to `__sync_bool_compare_and_swap_8'
gradient.c:(.text+0x1879): undefined reference to`__sync_bool_compare_and_swap_8'
/tmp/ccuPItVc.o: In function `grd_flupgrad':
gradient.c:(.text+0x19be): undefined reference to`__sync_bool_compare_and_swap_8'
/tmp/ccuPItVc.o:gradient.c:(.text+0x1b06): more undefined references to `__sync_bool_compare_and_swap_8' follow
collect2: ld returned 1 exit status
make: **\* [wapiti] Error 1

**Comment by linzhi** [comment]
build success on ubuntu 12.04.....

**Comment by mountain** [comment]
Thanks for your feedback!
